### ISSUE TITLE
Duplicates in the language list

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#45] opened 2016-12-10 10:57 UTC
I have a lots of duplicates in the content manager language list. For example "Low German", "Lower Sorbian", "Ligurian", etc... I dozen of languages have duplicates.

**Comment by automactic** [comment] 2017-01-21 20:08
What do you mean? Do you see the exact duplicate? For example two "German". They could be different dialect of the same lang family

**Comment by kelson42** [comment] 2017-01-22 16:25
Yes I see duplicates. We should find a solution to difference them (if they are not pointing to the same language).

**Comment by Popolechien** [comment] 2017-01-31 07:33
Got the exact same comment today in the OTRS feeback queue:
"Hello,
on my first iPod i have 36 books abailable for download, some of them  twice. On my other
iPod there are 51 books abailable for download, some of them even three times.
What's wrong?
Best regards"

**Comment by automactic** [comment] 2017-01-31 19:12
@Popolechien, I can't think of why this could happen. App will always check if book with an id or a language with a code exist before inserting a new one. If the user is using an earlier version or upgrade from an earlier version, it might be possible that the app allows 2 background threads to download library.xml and process at the same time. 

In upcoming version 1.8, the underlying SQLite store will have unique constraint on the id field of book and on code field of language. Duplicates will be discarded during the upgrade process.

An extra note regarding languages: all language code will be converted to canonical form, e.g. "eng" -> "en"

**Comment by Popolechien** [comment] 2017-02-01 06:36
Ok, thanks for the clarification!

**Comment by automactic** [comment] 2017-02-24 16:50
Closing this, since there is no way to reproduce

**Closed by automactic** 2017-02-24 16:50 UTC
Labels: bug
