### ISSUE TITLE
Bug report on Sourceforge

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#39] opened 2016-10-24 10:32 UTC
iPhone 6s, running latest iOs 9.

Have the kiwix app with a number of offline wikis downloaded.

Enter search screen, enter "f", application quits immediately when push "space" following that.
If enter search beginning with "f" and continue typing other letters but not yet "space", application quits following second or two.

Have not encountered this except in search beginning with F.

Was not able to create new topic/ticket in dedicated bug section.

https://sourceforge.net/p/kiwix/discussion/604122/thread/f852b10c/?limit=25#0366

**Comment by automactic** [comment] 2017-01-31 19:23
Lack of info, which sim does the user have? Do they have idx folder or embedded index? Closing this since there is no way to reproduce

**Closed by automactic** 2017-01-31 19:23 UTC
Labels: bug
