### ISSUE TITLE
Favorites are not saved correctly in IOS 

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#43] opened 2016-11-20 10:24 UTC
I have currently Kiwix 1.7.1 for Ios installed on my iphone. I have downloaded the database Wikivoyage (complete version). When you bookmark/favoritize an article, it stores it, but the same disappears a while and once you exit the application.

Would appreciate your input on this bug and when it is expected to be resolved if at all.
Thanks

This bug was previously reported at: https://sourceforge.net/p/kiwix/bugs/961/

**Comment by kelson42** [comment] 2016-11-20 10:24
Thank you for your bug report. Unfortunately I'm not able to reproduce that problem. What we know is that if you download a new version of the Wikivoyage content, then your bookmarks will disappear. But this seems to be another problem and we are going to fix the other one.

**Comment by automactic** [comment] 2017-01-21 20:08
Closing this, since there is no way to reproduce

**Closed by automactic** 2017-01-21 20:08 UTC
Labels: bug
